version: "3"
services:
  node_server:
    container_name: "docker-demo-container"
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
    - "3001:3001"
    volumes:
    - '.:/var/server'
